KatyDevBlog/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KatyDevBlog.Data;
using KatyDevBlog.Models;
using KatyDevBlog.Services.Interfaces;
using KatyDevBlog.Enums;
using Microsoft.AspNetCore.Authorization;
using KatyDevBlog.Services;
using X.PagedList;

namespace KatyDevBlog.Controllers
{
    public class BlogPostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly ISlugService _slugService;
        private readonly SearchService _searchService;

        public BlogPostsController(ApplicationDbContext context, IImageService imageService, ISlugService slugService, SearchService searchService)
        {
            _context = context;
            _imageService = imageService;
            _slugService = slugService;
            _searchService = searchService;
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchPosts(int? page, string searchTerm)
        {
            //I need to have a good page number and page might come in as null
            var pageNumber = page ?? 1;
            var pageSize = 7;

            //In order to propagate the search term from one page to the next I will
            //use a ViewData to push the term into the view
            ViewData["SearchTerm"] = searchTerm;

            var blogPosts = await _searchService.SearchAsync(searchTerm);
            return View(await blogPosts.ToPagedListAsync(pageNumber, pageSize));
        }

        public async Task<IActionResult> ChildIndex(int blogId)
        {
            //I don't want to get all of the BlogPosts....
            //I want to get all of the BlogPosts where the BlogId = blogId
            //Also...I only want to grab production ready BlogPosts
            var blogPosts = _context.BlogPosts
                .Include(b => b.Blog)
                .Where(b => b.BlogId == blogId && b.ReadyStatus == ReadyState.Ready)
                .OrderByDescending(b => b.Created);

            return View(await blogPosts.ToListAsync());

        }

        // GET: BlogPosts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BlogPosts
                .Include(b => b.Blog)
                .Where(b => b.ReadyStatus == ReadyState.Ready)
                .OrderByDescending(b => b.Created);

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Preview()
        {
            var blogPosts = _context.BlogPosts
               .Include(b => b.Blog)
               .Where(b => b.ReadyStatus == ReadyState.InPreview)
               .OrderByDescending(b => b.Created);

            return View("Index", await blogPosts.ToListAsync());
        }

        public async Task<IActionResult> Details(string slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts
                .Include(b => b.Blog)
                .Include(b => b.Tags)
                .Include(b => b.Comments)
                .ThenInclude(c => c.BlogUser)
                .FirstOrDefaultAsync(m => m.Slug == slug);

            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        public async Task<IActionResult> TagIndex(string tag, int? page)
        {
            //Start with my pageing data
            var pageNumber = page ?? 1;
            var pageSize = 6;

            var allBlogPostIds = _context.Tags.Where(t => t.Text.ToLower() == tag.ToLower())
                                              .Select(t => t.BlogPostId);

            var blogPosts = await _context.BlogPosts
                                        .Where(b => allBlogPostIds.Contains(b.Id))
                                        .OrderByDescending(b => b.Created)
                                        .ToPagedListAsync(pageNumber, pageSize);

            ViewData["Tag"] = tag;
            return View(blogPosts);
        }



        // GET: BlogPosts/Create
        [Authorize(Roles ="Administrator")]
        public IActionResult Create(int? blogId)
        {
            if (blogId is not null)
            {
                BlogPost newBlogPost = new()
                {
                    BlogId = (int)blogId
                };

                return View(newBlogPost);
            }

            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name");
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogId,Title,Abstract,Content,ReadyStatus,Image")] BlogPost blogPost, List<string> tagValues)
        {
            if (ModelState.IsValid)
            {
                //Let's create and check the slug for uniqueness
                var slug = _slugService.UrlFriendly(blogPost.Title);
                if (!_slugService.IsUnique(slug))
                {
                    //Create a custom Model Error and complain to the user
                    ModelState.AddModelError("Title", "Error: Title has already been used.");
                    return View(blogPost);
                }
                else
                {
                    blogPost.Slug = slug;
                }

                //Either record the incoming image or use the default image
                if (blogPost.Image is not null)
                {
                    if (!_imageService.ValidImage(blogPost.Image))
                    {
                        ModelState.AddModelError("Image", "Please choose a valid image.");
                        return View(blogPost);
                    }
                    else
                    {
                        blogPost.ImageData = await _imageService.EncodeImageAsync(blogPost.Image);
                        blogPost.ImageType = _imageService.ImageType(blogPost.Image);
                    }
                }
                else
                {
                    blogPost.ImageData = await _imageService.EncodeImageAsync("newpost.png");
                    blogPost.ImageType = "png";
                }

                blogPost.Created = DateTime.Now;

                _context.Add(blogPost);
                await _context.SaveChangesAsync();

                foreach (var tag in tagValues)
                {
                    _context.Add(new Tag()
                    {
                        BlogPostId = blogPost.Id,
                        Text = tag
                    });
                }

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name", blogPost.BlogId);
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts.FindAsync(id);
            if (blogPost == null)
            {
                return NotFound();
            }
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Description", blogPost.BlogId);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BlogId,Title,Abstract,Content,Created,ReadyStatus,Slug,ImageData,ImageType,Image")] BlogPost blogPost)
        {
            if (id != blogPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //In the Edit we have to make sure that the Title actually changed before checking slug uniqueness                    
                    var slug = _slugService.UrlFriendly(blogPost.Title);
                    if (slug != blogPost.Slug)
                    {
                        if (!_slugService.IsUnique(slug))
                        {
                            //Create a custom Model Error and complain to the user
                            ModelState.AddModelError("Title", "Error: Title has already been used.");
                            return View(blogPost);
                        }
                        else
                        {
                            blogPost.Slug = slug;
                        }
                    }

                    blogPost.Updated = DateTime.Now;
                    _context.Update(blogPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogPostExists(blogPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Description", blogPost.BlogId);

KatyDevBlog/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KatyDevBlog.Data;
using KatyDevBlog.Models;
using KatyDevBlog.Services.Interfaces;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace KatyDevBlog.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context; //Class Member
        private readonly IImageService _imageService;
        private readonly ISlugService _slugService;

        public BlogsController(ApplicationDbContext context, IImageService imageService, ISlugService slugService)
        {
            //Dependency Injection
            _context = context;// constructor
            _imageService = imageService;
            _slugService = slugService;
        }

        // GET: Blogs
        public async Task<IActionResult> Index(int? page)
        {

            //Page might be null... if it is I'll update to be 1
            {
                var pageNumber = page ?? 1;
                var pageSize = 5;

                var blogs = await _context.Blogs.OrderBy(b => b.Created).ToPagedListAsync(pageNumber, pageSize);
                return View(blogs);

            }
        }
                // GET: Blogs/Details/5
                public async Task<IActionResult> Details(string slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .FirstOrDefaultAsync(m => m.Slug == slug);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        [Authorize (Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Image")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                //Let's create and check the slug for uniqueness
                var slug = _slugService.UrlFriendly(blog.Name);
                if (!_slugService.IsUnique(slug))
                {
                    //Create a custom Model Error and complain to the user
                    ModelState.AddModelError("Title", "Error: Title has already been used.");
                    return View(blog);
                }
                else
                {
                    blog.Slug = slug;
                }
                if (blog.Image is null)
                {
                    blog.ImageData = await _imageService.EncodeImageAsync("newblog.png");
                    blog.ImageType = "png";
                }
                else
                {
                    if (!_imageService.ValidImage(blog.Image))
                    {
                        //We need to add a custom Model Error and inform the user
                        ModelState.AddModelError("Image", "Please choose a valid image");
                        return View(blog);
                    }
                    else
                    {
                        blog.ImageData = await _imageService.EncodeImageAsync(blog.Image);
                        blog.ImageType = _imageService.ImageType(blog.Image);
                    }
                }
                //Programmatically add in the Created Date
                blog.Created = DateTime.Now;
                //Adds new blog record to DbSet<Blog>
                _context.Add(blog);
                //This line generates Id
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Created,Image,ImageData,ImageType")] Blog blog)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Did the user choose a NEW image
                    if(blog.Image is not null)
                    {
                        //If the image fails validation, complain to the user
                        if (!_imageService.ValidImage(blog.Image))
                        {
                            ModelState.AddModelError("Image", "There was a problem with the image, please choose another one.");
                            return View(blog);
                        }
                        else
                        {
                            blog.ImageData = await _imageService.EncodeImageAsync(blog.Image);
                            blog.ImageType = _imageService.ImageType(blog.Image);
                        }
                    }

                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blogs.FindAsync(id);
            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.Id == id);
        }
    }
}

KatyDevBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>KatyDev Blog</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="DevCard Bootstrap 5 Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="~/kp-mark-light3.ico">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">



    <!-- Theme CSS -->
    <link href="~/css/theme-9.css" rel="stylesheet" />
    <link href="~/css/custom.css" rel="stylesheet" />

</head>

<body>

    <header class="header text-center">
        <div class="force-overflow">
            <h1 class="blog-name pt-lg-4 mb-0"><a class="no-text-decoration" href="index.html">Katherine Pitts</a></h1>

            <nav class="navbar navbar-expand-lg navbar-dark">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div id="navigation" class="collapse navbar-collapse flex-column">
                    <div class="profile-section pt-3 pt-lg-0">
                        <img class="profile-image mb-3 rounded-circle mx-auto" src="/img/profile-img.jpg" alt="image">

                        <div class="bio mb-3">Hi, my name is Katherine Pitts and I'm a software engineer. Welcome to my tech blog!</div><!--//bio-->
                        <ul class="social-list list-inline py-2 mx-auto">
                            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>

                        </ul><!--//social-list-->
                        <hr>
                    </div><!--//profile-section-->

                    <ul class="navbar-nav flex-column text-start">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index"><i class="fas fa-user fa-fw me-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Blogs" asp-action="Index"><i class="fas fa-laptop-code fa-fw me-2"></i>Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="BlogPosts" asp-action="Index"><i class="fas fa-briefcase fa-fw me-2"></i>All Posts</a>
                        </li>
                        <!-- A Search Form -->

                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Blogs" asp-action="Create"><i class="fas fa-file-alt fa-fw me-2"></i>Create New Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="BlogPosts" asp-action="Create"><i class="fas fa-file-alt fa-fw me-2"></i>Create New Blog Post</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="ContactMe"><i class="fas fa-envelope-open-text fa-fw me-2"></i>Contact</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                    
                    <form asp-action="SearchPosts" asp-controller="BlogPosts">
                            <input type="text" name="searchTerm" class="px-3" />
                            <button class="btn btn-sm btn-dark w-100">Search</button>
                    </form>
                    







                    <div class="dark-mode-toggle text-center w-100">
                        <hr class="mb-4">
                        <h4 class="toggle-name mb-3 "><i class="fas fa-adjust me-1"></i>Dark Mode</h4>

                        <input class="toggle" id="darkmode" type="checkbox">
                        <label class="toggle-btn mx-auto mb-0" for="darkmode"></label>

                    </div><!--//dark-mode-toggle-->
                </div>
            </nav>
        </div><!--//force-overflow-->
    </header>

    <div class="main-wrapper">
        <div class="container-fluid">
            @RenderBody()
        </div>
        


        <footer class="footer text-center py-4">
            <small class="copyright">Template Copyright &copy; <a href="https://themes.3rdwavemedia.com/" target="_blank">3rd Wave Media</a></small>
        </footer>

    </div><!--//main-wrapper-->
    <!-- FontAwesome JS -->
    <script src="~/js/all.js"></script>
    <!-- Javascript -->
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>

    <!-- Dark Mode -->
    <script src="~/js/js-cookie.min.js"></script>
    <script src="~/js/dark-mode.js"></script>



    <script src="https://cdn.tiny.cloud/1/6ccwhxbeo8t47dj17g9r8gb8i9qjivdnue6qsy1eo7dt2sld/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea#Content',
            plugins: 'image code',
            toolbar: 'undo redo | link image | code',
            /* enable title field in the Image dialog*/
            image_title: true,
            /* enable automatic uploads of images represented by blob or data URIs*/
            automatic_uploads: true,
            /*
              URL of our upload handler (for more details check: https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_url)
              images_upload_url: 'postAcceptor.php',
              here we add custom filepicker only to Image dialog
            */
            file_picker_types: 'image',
            /* and here's our custom image picker*/
            file_picker_callback: function (cb, value, meta) {
                var input = document.createElement('input');
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*');

                /*
                  Note: In modern browsers input[type="file"] is functional without
                  even adding it to the DOM, but that might not be the case in some older
                  or quirky browsers like IE, so you might want to add it to the DOM
                  just in case, and visually hide it. And do not forget do remove it
                  once you do not need it anymore.
                */

                input.onchange = function () {
                    var file = this.files[0];

                    var reader = new FileReader();
                    reader.onload = function () {
                        /*
                          Note: Now we need to register the blob in TinyMCEs image blob
                          registry. In the next release this part hopefully won't be
                          necessary, as we are looking to handle it internally.
                        */
                        var id = 'blobid' + (new Date()).getTime();
                        var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                        var base64 = reader.result.split(',')[1];
                        var blobInfo = blobCache.create(id, file, base64);
                        blobCache.add(blobInfo);

                        /* call the callback and populate the Title field with the file name */
                        cb(blobInfo.blobUri(), { title: file.name });
                    };
                    reader.readAsDataURL(file);
                };

                input.click();
            },
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>